package io.thernal.buildkit.buildlogic.environment

/** The Kotlin source of the generated object: one `const val` per key, plus the flavor itself. */
internal fun environmentSource(
    packageName: String,
    objectName: String,
    flavor: String,
    isProduction: Boolean,
    fields: Map<String, String>,
): String = buildString {
    appendLine("// Generated by build-kit from .env.$flavor — do not edit; change the .env file instead.")
    appendLine("package $packageName")
    appendLine()
    appendLine("public object $objectName {")
    appendLine("    public const val FLAVOR: String = ${flavor.kotlinString()}")
    appendLine("    public const val IS_PRODUCTION: Boolean = $isProduction")
    fields.toSortedMap().forEach { (key, value) ->
        appendLine("    public const val $key: String = ${value.kotlinString()}")
    }
    appendLine("}")
}

private fun String.kotlinString(): String = buildString {
    append('"')
    this@kotlinString.forEach { character ->
        when (character) {
            '\\' -> append("\\\\")
            '"' -> append("\\\"")
            '$' -> append("\\$")
            '\n' -> append("\\n")
            '\r' -> append("\\r")
            '\t' -> append("\\t")
            else -> append(character)
        }
    }
    append('"')
}
