package io.thernal.buildkit.buildlogic

import java.io.File
import java.util.Locale
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault

internal const val STABILITY_REPORT_FILE = "compose-stability.md"

/** One module's Compose compiler metrics (`*-module.json`) and the classes it reports unstable. */
internal data class ModuleStability(
    val path: String,
    val fields: Map<String, Int>,
    val unstableClasses: List<String>,
)

/**
 * Aggregates the Compose compiler's per-module metrics — written only by a build run with
 * `-PcomposeStabilityReport=true` — into `report/compose-stability.md`: generated, never edited by
 * hand, and merged like the module report.
 */
@DisableCachingByDefault(because = "Reads metric files other tasks wrote, whatever they were")
abstract class ComposeStabilityReportTask : DefaultTask() {
    @get:Internal abstract val repositoryDirectory: DirectoryProperty
    @get:Internal abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun writeReport() {
        val root = repositoryDirectory.get().asFile
        val metricsFiles = root.walkTopDown()
            .onEnter { it.name !in setOf(".git", ".gradle", "build-logic", "src") }
            .filter { it.isFile && it.name.endsWith("-module.json") && "/build/compose-metrics/" in it.invariantSeparatorsPath }
            .sortedBy(File::getAbsolutePath)
            .toList()
        if (metricsFiles.isEmpty()) {
            logger.lifecycle("No Compose compiler metrics found; build with -P$STABILITY_REPORT_PROPERTY=true first.")
            return
        }
        val modules = metricsFiles
            .map { file ->
                ModuleStability(
                    path = moduleGradlePath(file, root),
                    fields = parseModuleMetrics(file.readText()),
                    unstableClasses = unstableClasses(reportsDirectoryFor(file)),
                )
            }
            // A multiplatform module compiles Compose once per target; its first metrics file stands in.
            .distinctBy(ModuleStability::path)
            .sortedBy(ModuleStability::path)

        val output = outputDirectory.get().asFile.apply { mkdirs() }.resolve(STABILITY_REPORT_FILE)
        output.writeText(renderStabilityReport(modules))
        logger.lifecycle("Wrote ${output.relativeTo(root)} from ${modules.size} module(s).")
    }
}

internal fun parseModuleMetrics(text: String): Map<String, Int> =
    Regex(""""(\w+)"\s*:\s*(-?\d+)""").findAll(text).associate { it.groupValues[1] to it.groupValues[2].toInt() }

internal fun moduleGradlePath(metricsFile: File, root: File): String =
    ":" + metricsFile.relativeTo(root).invariantSeparatorsPath.substringBefore("/build/compose-metrics/").replace('/', ':')

/** `build/compose-metrics/devDebug/x-module.json` → `build/compose-reports/devDebug`: the compiler mirrors the layout. */
internal fun reportsDirectoryFor(metricsFile: File): File {
    val path = metricsFile.parentFile.invariantSeparatorsPath
    return File(path.replace("/build/compose-metrics", "/build/compose-reports"))
}

private fun unstableClasses(reportsDirectory: File): List<String> =
    reportsDirectory.listFiles { file -> file.name.endsWith("-classes.txt") }
        ?.sortedBy(File::getName)
        ?.firstOrNull()
        ?.readLines()
        ?.filter { it.startsWith("unstable class ") }
        ?.map { it.removePrefix("unstable class ").substringBefore(" {").trim() }
        .orEmpty()

private fun percent(part: Int, total: Int): String =
    if (total == 0) "n/a" else String.format(Locale.ROOT, "%.1f%%", part * 100.0 / total)

internal fun renderStabilityReport(modules: List<ModuleStability>): String = buildString {
    fun sum(field: String) = modules.sumOf { it.fields[field] ?: 0 }
    val composables = sum("totalComposables")
    val skippable = sum("skippableComposables")
    val restartable = sum("restartableComposables")
    val classes = sum("totalClasses")
    val stable = sum("effectivelyStableClasses")

    appendLine("# Compose Stability Report")
    appendLine()
    appendLine("Generated by `./gradlew composeStabilityReport` from Compose compiler metrics (`-P$STABILITY_REPORT_PROPERTY=true`). Do not edit by hand.")
    appendLine()
    appendLine("A skippable composable recomposes only when its inputs change. It loses that the moment it takes an")
    appendLine("unstable parameter — most often a class the compiler cannot prove stable; list it in")
    appendLine("`$STABILITY_CONFIGURATION_FILE` or mark it `@Immutable`/`@Stable`.")
    appendLine()
    appendLine("## At a glance")
    appendLine()
    appendLine("| | |")
    appendLine("|---|---|")
    appendLine("| Modules with Compose metrics | ${modules.size} |")
    appendLine("| Composables | $composables |")
    appendLine("| Skippable | $skippable (${percent(skippable, composables)}) |")
    appendLine("| Restartable | $restartable (${percent(restartable, composables)}) |")
    appendLine("| Classes | $classes |")
    appendLine("| Effectively stable | $stable (${percent(stable, classes)}) |")
    appendLine()
    appendLine("## Per module")
    appendLine()
    appendLine("| Module | Composables | Skippable | Classes | Stable | Unstable classes |")
    appendLine("|---|---|---|---|---|---|")
    modules.forEach { module ->
        val total = module.fields["totalComposables"] ?: 0
        val moduleClasses = module.fields["totalClasses"] ?: 0
        val unstable = when {
            module.unstableClasses.isEmpty() -> "—"
            module.unstableClasses.size > MAX_LISTED_CLASSES -> module.unstableClasses.take(MAX_LISTED_CLASSES).joinToString(", ") + ", …"
            else -> module.unstableClasses.joinToString(", ")
        }
        appendLine(
            "| `${module.path}` | $total | ${percent(module.fields["skippableComposables"] ?: 0, total)} | " +
                "$moduleClasses | ${percent(module.fields["effectivelyStableClasses"] ?: 0, moduleClasses)} | $unstable |",
        )
    }
}

private const val MAX_LISTED_CLASSES = 5
