package io.thernal.buildkit.buildlogic

import org.gradle.api.Project

private val ENVIRONMENT_KEY = Regex("[A-Z][A-Z0-9_]*")

/** Keys the generated object declares itself; a `.env` file may not redefine them. */
internal val RESERVED_ENVIRONMENT_KEYS = setOf("FLAVOR", "IS_PRODUCTION")

/**
 * `KEY=value` lines of the repository-root `.env.<flavor>` files, aligned across every flavor.
 *
 * Every flavor exposes the same keys, so code that reads one compiles whichever flavor is built: a
 * key only some flavors declare, a missing file and an unreadable line are warnings that fall back
 * to an empty value, never another flavor's.
 */
internal fun Project.environmentFields(flavors: AppFlavors): Map<String, Map<String, String>> {
    val declared = flavors.all.associateWith { readEnvironmentFile(it) }
    val keys = declared.values.flatMapTo(sortedSetOf()) { it.keys }
    val fields = declared.mapValues { (_, entries) -> keys.associateWith { entries[it].orEmpty() } }

    val blank = fields.flatMap { (flavor, entries) ->
        entries.filterValues(String::isBlank).keys.map { ".env.$flavor $it" }
    }
    if (blank.isNotEmpty()) {
        logger.warn("$path: empty environment values, building with empty strings: ${blank.joinToString()}")
    }
    return fields
}

private fun Project.readEnvironmentFile(flavor: String): Map<String, String> {
    val file = rootProject.layout.projectDirectory.file(".env.$flavor")
    val content = providers.fileContents(file).asText.orNull
    if (content == null) {
        logger.warn("$path: missing environment file ${file.asFile}; treating it as empty")
        return emptyMap()
    }
    return parseEnvironment(content) { line -> logger.warn("$path: ignoring '$line' in .env.$flavor; expected UPPER_SNAKE_KEY=value") }
}

internal fun parseEnvironment(content: String, onInvalid: (String) -> Unit): Map<String, String> =
    content.lineSequence()
        .map(String::trim)
        .filter { it.isNotEmpty() && !it.startsWith("#") }
        .mapNotNull { line ->
            val key = line.substringBefore('=').trim()
            if (!line.contains('=') || !key.matches(ENVIRONMENT_KEY) || key in RESERVED_ENVIRONMENT_KEYS) {
                onInvalid(line)
                null
            } else {
                key to line.substringAfter('=').trim()
            }
        }
        .toMap()

/** The Kotlin source of the generated object: one `const val` per key, plus the flavor itself. */
internal fun environmentSource(
    packageName: String,
    objectName: String,
    flavor: String,
    isProduction: Boolean,
    fields: Map<String, String>,
): String = buildString {
    appendLine("// Generated by build-kit from .env.$flavor — do not edit; change the .env file instead.")
    appendLine("package $packageName")
    appendLine()
    appendLine("public object $objectName {")
    appendLine("    public const val FLAVOR: String = ${flavor.kotlinString()}")
    appendLine("    public const val IS_PRODUCTION: Boolean = $isProduction")
    fields.toSortedMap().forEach { (key, value) ->
        appendLine("    public const val $key: String = ${value.kotlinString()}")
    }
    appendLine("}")
}

private fun String.kotlinString(): String = buildString {
    append('"')
    this@kotlinString.forEach { character ->
        when (character) {
            '\\' -> append("\\\\")
            '"' -> append("\\\"")
            '$' -> append("\\$")
            '\n' -> append("\\n")
            '\r' -> append("\\r")
            '\t' -> append("\\t")
            else -> append(character)
        }
    }
    append('"')
}
