package io.thernal.buildkit.buildlogic

import java.io.File
import java.io.Serializable
import java.util.Locale

/**
 * One module and the modules it declares a dependency on. [area] is the first directory under the
 * modules root (`app.modules.root`): `core` for `:core:network:api`, and for `:fixture:core:x` too
 * when the root is `fixture`.
 */
data class ModuleNode(
    val path: String,
    val area: String,
    val sourceDirectory: String,
    val dependencies: List<String>,
) : Serializable {

    /** `api`, `impl`, `wiring`, or null for a module that is not part of a capability split. */
    val role: String? get() = path.substringAfterLast(':').takeIf { it in ROLES }

    private companion object {
        val ROLES = setOf("api", "impl", "wiring")
        const val serialVersionUID = 1L
    }
}

/**
 * Coupling metrics from Robert Martin's package principles, computed per module.
 *
 * - [afferent] (Ca): modules that depend on this one.
 * - [efferent] (Ce): modules this one depends on.
 * - [instability] (I): `Ce / (Ca + Ce)`. `0.0` is maximally stable, `1.0` maximally unstable.
 * - [abstractness] (A): share of top-level declarations that are interfaces or abstract classes.
 * - [distance] (D): `|A + I - 1|`. Distance from the main sequence, where `0.0` is balanced.
 */
data class ModuleMetrics(
    val path: String,
    val afferent: Int,
    val efferent: Int,
    val instability: Double,
    val abstractness: Double,
    val distance: Double,
    val declarations: Int,
) : Serializable {
    private companion object {
        const val serialVersionUID = 1L
    }
}

/** Renders the module report as one file per view, plus an index that links them together. */
internal object ModuleGraph {

    const val INDEX = "README.md"

    private val ABSTRACT_DECLARATION = Regex(
        """^\s*(?:public |internal |private )?(?:sealed |abstract |fun )?interface\s|""" +
            """^\s*(?:public |internal |private )?(?:sealed|abstract)\s+class\s""",
        RegexOption.MULTILINE,
    )
    private val CONCRETE_DECLARATION = Regex(
        """^\s*(?:public |internal |private )?(?:data |value |enum |annotation )?(?:class|object)\s""",
        RegexOption.MULTILINE,
    )

    private val GRAPHS = listOf(
        Graph("core.md", "Core", "Modules under `core/`, the shared capability layer.") { it.area == "core" },
        Graph("features.md", "Features", "Modules under `features/`, grouped by owner.") { it.area == "features" },
        Graph(
            file = "core-and-features.md",
            title = "Core and features",
            blurb = "How product features consume core capabilities.",
        ) { it.area == "core" || it.area == "features" },
        Graph("all-modules.md", "All modules", "Every module in the build, apps included.") { true },
    )

    /** Returns the report as file name to Markdown content. */
    fun render(
        modules: List<ModuleNode>,
        task: String,
    ): Map<String, String> {
        val known = modules.map(ModuleNode::path).toSet()
        val roles = modules.associate { module -> module.path to module.role }
        val metrics = metrics(modules, known).associateBy(ModuleMetrics::path)
        val conditions = modules.associate { module ->
            module.path to Condition.of(module, metrics.getValue(module.path)) { path -> roles[path] }
        }
        val waves = waves(modules, known)

        return buildMap {
            put(INDEX, index(modules, conditions, waves, task))
            put("health.md", page("Health", task) { append(health(modules, metrics, conditions)) })
            put("build-waves.md", page("Build waves", task) { append(buildWaves(waves)) })
            GRAPHS.forEach { graph ->
                put(
                    graph.file,
                    page(graph.title, task) {
                        appendLine(graph.blurb)
                        appendLine()
                        append(arrowLegend())
                        appendLine()
                        append(mermaid(modules.filter(graph.include), known, conditions))
                    },
                )
            }
            put("metrics.md", page("Coupling metrics", task) { append(rawMetrics(modules.mapNotNull { metrics[it.path] })) })
        }
    }

    // ---------------------------------------------------------------- index

    private fun index(
        modules: List<ModuleNode>,
        conditions: Map<String, Condition>,
        waves: List<List<String>>,
        task: String,
    ): String = buildString {
        appendLine("# Module Report")
        appendLine()
        appendLine("Generated by `./gradlew $task`. Do not edit by hand.")
        appendLine()
        appendLine(summary(conditions.values.toList()))
        appendLine()
        appendLine("| Page | What it answers |")
        appendLine("|---|---|")
        appendLine("| [Health](health.md) | Which modules need attention, and what to do about each |")
        appendLine("| [Build waves](build-waves.md) | What compiles in parallel, and in what order to read the code |")
        GRAPHS.forEach { graph ->
            appendLine("| [${graph.title}](${graph.file}) | ${modules.count(graph.include)} modules |")
        }
        appendLine("| [Coupling metrics](metrics.md) | The raw afferent, efferent, instability and abstractness figures |")
        appendLine()
        appendLine("## At a glance")
        appendLine()
        appendLine("| | |")
        appendLine("|---|---|")
        appendLine("| Modules | ${modules.size} |")
        appendLine("| Build depth | ${waves.size} waves |")
        appendLine("| Widest wave | ${waves.maxOfOrNull(List<String>::size) ?: 0} modules in parallel |")
        val flagged = conditions.entries
            .filter { entry -> entry.value.severity != Severity.HEALTHY }
            .sortedWith(compareBy({ it.value.severity.ordinal }, { it.value.ordinal }, { it.key }))
        if (flagged.isNotEmpty()) {
            appendLine()
            appendLine("## Needs a look")
            appendLine()
            flagged.forEach { (path, condition) ->
                appendLine("- ${condition.severity.marker} `$path` — **${condition.title}**. ${condition.action}")
            }
            appendLine()
            appendLine("[Full health table](health.md)")
        }
    }

    private fun page(
        title: String,
        task: String,
        body: StringBuilder.() -> Unit,
    ): String = buildString {
        appendLine("# $title")
        appendLine()
        appendLine("[← Module report](${INDEX}) · generated by `./gradlew $task`")
        appendLine()
        body()
        appendLine()
        appendLine("[← Module report](${INDEX})")
    }

    private fun summary(conditions: List<Condition>): String {
        val counts = Severity.entries.associateWith { severity ->
            conditions.count { condition -> condition.severity == severity }
        }
        return Severity.entries.joinToString(separator = " · ") { severity ->
            "${severity.marker} ${counts.getValue(severity)} ${severity.label.lowercase(Locale.ROOT)}"
        }
    }

    // ---------------------------------------------------------------- pages

    private fun health(
        modules: List<ModuleNode>,
        metrics: Map<String, ModuleMetrics>,
        conditions: Map<String, Condition>,
    ): String = buildString {
        appendLine("Each module gets the first condition that applies to it, so the verdict is one thing to act on")
        appendLine("rather than a row of numbers. **Used by** counts the modules that depend on it, **depends on**")
        appendLine("the modules it needs.")
        appendLine()
        Condition.entries.forEach { condition ->
            appendLine("- ${condition.severity.marker} **${condition.title}** — ${condition.meaning} ${condition.action}")
        }
        appendLine()
        appendLine("| | Module | Condition | Used by | Depends on |")
        appendLine("|---|---|---|---:|---:|")
        modules
            .sortedWith(
                compareBy<ModuleNode> { conditions.getValue(it.path).severity.ordinal }
                    .thenBy { conditions.getValue(it.path).ordinal }
                    .thenBy(ModuleNode::path),
            )
            .forEach { module ->
                val condition = conditions.getValue(module.path)
                val entry = metrics.getValue(module.path)
                appendLine(
                    "| ${condition.severity.marker} | `${module.path}` | ${condition.title} " +
                        "| ${entry.afferent} | ${entry.efferent} |",
                )
            }
    }

    private fun buildWaves(waves: List<List<String>>): String = buildString {
        appendLine("A wave is everything that can compile at once: wave 0 depends on no other module, and each")
        appendLine("later wave waits only for the ones before it. The build is at least this many steps deep no")
        appendLine("matter how many cores are available, so a deep graph is a slow graph.")
        appendLine()
        appendLine("Read the code in the same order. Wave 0 stands on its own; by the time you reach a later")
        appendLine("wave you have already seen everything it builds on.")
        appendLine()
        appendLine("| Wave | Parallel |")
        appendLine("|---:|---:|")
        waves.forEachIndexed { index, wave -> appendLine("| $index | ${wave.size} |") }
        appendLine()
        waves.forEachIndexed { index, wave ->
            appendLine("## Wave $index")
            appendLine()
            appendLine("${wave.size} modules, all buildable at the same time.")
            appendLine()
            append(waveRow(wave))
            appendLine()
        }
    }

    /**
     * One diagram per wave, so the waves stack simply by being separate blocks.
     *
     * Inside a wave the modules are chained with Mermaid's invisible link. They have no real
     * dependency on each other, but a link is what gives them separate ranks, and in `LR` separate
     * ranks run left to right — the row that shows the wave building at once. Without it they share
     * a rank and render as a column, which reads like a sequence they are not.
     */
    private fun waveRow(wave: List<String>): String {
        val sorted = wave.sorted()
        if (sorted.isEmpty()) return "_Empty wave._\n"

        return buildString {
            appendLine("```mermaid")
            appendLine("graph LR")
            sorted.forEach { path ->
                appendLine("  ${identifier(path)}[\"${path.removePrefix(":")}\"]")
            }
            sorted.zipWithNext().forEach { (left, right) ->
                appendLine("  ${identifier(left)} ~~~ ${identifier(right)}")
            }
            appendLine("```")
        }
    }

    private fun arrowLegend(): String = buildString {
        appendLine("An arrow points from a module to one it depends on. Node fill marks the role, and a 🔴 or 🟡")
        appendLine("repeats the verdict from [Health](health.md).")
    }

    private fun rawMetrics(metrics: List<ModuleMetrics>): String = buildString {
        appendLine("`Ca` counts the modules that depend on this one, `Ce` the modules it depends on.")
        appendLine("`I` is instability, `Ce / (Ca + Ce)`. `A` is abstractness, the share of declarations that are")
        appendLine("interfaces or abstract classes. `D` is `|A + I - 1|`, the distance from the main sequence.")
        appendLine()
        appendLine("A `wiring` module reads as fully abstract because a binding container is an interface, so its")
        appendLine("`D` is noise rather than a finding.")
        appendLine()
        appendLine("| Module | Ca | Ce | I | A | D | Declarations |")
        appendLine("|---|---:|---:|---:|---:|---:|---:|")
        metrics.sortedBy(ModuleMetrics::path).forEach { entry ->
            appendLine(
                "| `${entry.path}` | ${entry.afferent} | ${entry.efferent} | ${format(entry.instability)} " +
                    "| ${format(entry.abstractness)} | ${format(entry.distance)} | ${entry.declarations} |",
            )
        }
    }

    // ---------------------------------------------------------------- graph

    private fun mermaid(
        modules: List<ModuleNode>,
        known: Set<String>,
        conditions: Map<String, Condition>,
    ): String {
        if (modules.isEmpty()) return "_No modules in this view._\n"
        val visible = modules.map(ModuleNode::path).toSet()

        return buildString {
            appendLine("```mermaid")
            appendLine("graph LR")
            modules.groupBy(ModuleNode::area).toSortedMap().forEach { (area, areaModules) ->
                appendLine("  subgraph ${identifier(area)}[\"$area\"]")
                areaModules.sortedBy(ModuleNode::path).forEach { module ->
                    val marker = conditions[module.path]
                        ?.takeIf { condition -> condition.severity != Severity.HEALTHY }
                        ?.let { condition -> "${condition.severity.marker} " }
                        .orEmpty()
                    appendLine("    ${identifier(module.path)}[\"$marker${label(module.path)}\"]")
                }
                appendLine("  end")
            }
            modules.sortedBy(ModuleNode::path).forEach { module ->
                module.dependencies.filter { it in visible && it in known }.sorted().forEach { target ->
                    appendLine("  ${identifier(module.path)} --> ${identifier(target)}")
                }
            }
            appendLine("  classDef api fill:#e0eef2,stroke:#0d5c70,color:#0d5c70;")
            appendLine("  classDef impl fill:#f6ebd6,stroke:#8a6014,color:#8a6014;")
            appendLine("  classDef wiring fill:#e2efe8,stroke:#2c6a50,color:#2c6a50;")
            appendLine("  classDef app fill:#eae8f0,stroke:#5a5570,color:#5a5570;")
            listOf("api", "impl", "wiring").forEach { role ->
                val members = modules.filter { it.role == role }.map { identifier(it.path) }
                if (members.isNotEmpty()) appendLine("  class ${members.joinToString(",")} $role;")
            }
            val apps = modules.filter { it.area == "apps" }.map { identifier(it.path) }
            if (apps.isNotEmpty()) appendLine("  class ${apps.joinToString(",")} app;")
            appendLine("```")
        }
    }

    // ---------------------------------------------------------------- data

    private fun metrics(
        modules: List<ModuleNode>,
        known: Set<String>,
    ): List<ModuleMetrics> = modules.map { module ->
        val efferent = module.dependencies.filter { it in known }.distinct().size
        val afferent = modules.count { other ->
            other.path != module.path && module.path in other.dependencies
        }
        val coupling = afferent + efferent
        val instability = if (coupling == 0) 0.0 else efferent.toDouble() / coupling
        val (abstract, concrete) = declarationCounts(module.sourceDirectory)
        val declarations = abstract + concrete
        val abstractness = if (declarations == 0) 0.0 else abstract.toDouble() / declarations
        ModuleMetrics(
            path = module.path,
            afferent = afferent,
            efferent = efferent,
            instability = instability,
            abstractness = abstractness,
            distance = kotlin.math.abs(abstractness + instability - 1.0),
            declarations = declarations,
        )
    }

    /** Longest path from a leaf, so a module sits one wave after its deepest dependency. */
    private fun waves(
        modules: List<ModuleNode>,
        known: Set<String>,
    ): List<List<String>> {
        val edges = modules.associate { module ->
            module.path to module.dependencies.filter { it in known }.distinct()
        }
        val depth = mutableMapOf<String, Int>()

        fun depthOf(
            path: String,
            seen: Set<String>,
        ): Int = depth.getOrPut(path) {
            if (path in seen) return@getOrPut 0
            val dependencies = edges[path].orEmpty()
            if (dependencies.isEmpty()) 0 else dependencies.maxOf { depthOf(it, seen + path) } + 1
        }

        modules.forEach { module -> depthOf(module.path, emptySet()) }
        val grouped = modules.groupBy { module -> depth.getValue(module.path) }
        return (0..(grouped.keys.maxOrNull() ?: 0)).map { level ->
            grouped[level].orEmpty().map(ModuleNode::path)
        }
    }

    private fun declarationCounts(sourceDirectory: String): Pair<Int, Int> {
        val root = File(sourceDirectory)
        if (!root.isDirectory) return 0 to 0
        var abstract = 0
        var concrete = 0
        root.walkTopDown()
            .filter { file -> file.isFile && file.extension == "kt" }
            // Test source sets — `test`, `commonTest`, `androidHostTest`, `iosTest` — are not the
            // module's declarations.
            .filterNot { file -> file.relativeTo(root).invariantSeparatorsPath.substringBefore('/').let { it == "test" || it.endsWith("Test") } }
            .forEach { file ->
                val text = file.readText()
                abstract += ABSTRACT_DECLARATION.findAll(text).count()
                concrete += CONCRETE_DECLARATION.findAll(text).count()
            }
        return abstract to concrete
    }

    private fun format(value: Double): String = String.format(Locale.ROOT, "%.2f", value)

    /** `:core:network:api` -> `core_network_api`, which Mermaid accepts as a node id. */
    private fun identifier(value: String): String = value
        .removePrefix(":")
        .map { character -> if (character.isLetterOrDigit()) character else '_' }
        .joinToString(separator = "")

    /** Drops the area prefix, which the surrounding subgraph already shows. */
    private fun label(path: String): String {
        val withoutArea = path.removePrefix(":")
        return withoutArea.substringAfter(':', missingDelimiterValue = withoutArea)
    }

    private class Graph(
        val file: String,
        val title: String,
        val blurb: String,
        val include: (ModuleNode) -> Boolean,
    )
}
