package io.thernal.buildkit.buildlogic.compose.stability

import io.thernal.buildkit.buildlogic.compose.STABILITY_CONFIGURATION_FILE
import io.thernal.buildkit.buildlogic.compose.STABILITY_REPORT_PROPERTY
import java.util.Locale

private fun percent(part: Int, total: Int): String =
    if (total == 0) "n/a" else String.format(Locale.ROOT, "%.1f%%", part * 100.0 / total)

internal fun renderModuleStability(module: ModuleStability): String = buildString {
    fun field(name: String) = module.fields[name] ?: 0
    appendLine("# `${module.path}` — Compose stability")
    appendLine()
    appendLine("[← All modules]($INDEX_LINK) · generated by `./gradlew ${module.path}:$STABILITY_REPORT_TASK`. Do not edit by hand.")
    appendLine()
    appendLine("| | |")
    appendLine("|---|---|")
    appendLine("| Composables | ${field("totalComposables")} |")
    appendLine("| Skippable | ${field("skippableComposables")} (${percent(field("skippableComposables"), field("totalComposables"))}) |")
    appendLine("| Restartable | ${field("restartableComposables")} (${percent(field("restartableComposables"), field("totalComposables"))}) |")
    appendLine("| Classes | ${field("totalClasses")} |")
    appendLine("| Effectively stable | ${field("effectivelyStableClasses")} (${percent(field("effectivelyStableClasses"), field("totalClasses"))}) |")
    appendLine()
    appendLine("## Restartable but not skippable")
    appendLine()
    if (module.nonSkippableComposables.isEmpty()) {
        appendLine("None: every restartable composable here skips when its inputs are unchanged.")
    } else {
        appendLine("These recompose with their parent even when nothing they read changed — usually an unstable parameter.")
        appendLine()
        module.nonSkippableComposables.forEach { appendLine("- `$it`") }
    }
    appendLine()
    appendLine("## Unstable classes")
    appendLine()
    if (module.unstableClasses.isEmpty()) {
        appendLine("None.")
    } else {
        appendLine("Make them immutable, mark them `@Immutable`/`@Stable`, or list them in `$STABILITY_CONFIGURATION_FILE`.")
        appendLine()
        module.unstableClasses.forEach { appendLine("- `$it`") }
    }
}

internal fun renderStabilityIndex(modules: List<Pair<String, Map<String, Int?>>>): String = buildString {
    fun sum(field: String) = modules.sumOf { it.second[field] ?: 0 }
    appendLine("# Compose Stability")
    appendLine()
    appendLine("Generated by `./gradlew $STABILITY_REPORT_TASK` from Compose compiler metrics (`-P$STABILITY_REPORT_PROPERTY=true`). Do not edit by hand.")
    appendLine()
    appendLine("A skippable composable recomposes only when its inputs change. Each module's page lists the")
    appendLine("composables that cannot skip and the unstable classes behind them. A row of dashes is a page")
    appendLine("kept from an earlier run: that module was not built with metrics this time.")
    appendLine()
    appendLine("| | |")
    appendLine("|---|---|")
    appendLine("| Modules with Compose code | ${modules.size} |")
    appendLine("| Composables | ${sum("totalComposables")} |")
    appendLine("| Skippable | ${percent(sum("skippableComposables"), sum("totalComposables"))} |")
    appendLine("| Effectively stable classes | ${percent(sum("effectivelyStableClasses"), sum("totalClasses"))} |")
    appendLine()
    appendLine("| Module | Composables | Skippable | Classes | Stable |")
    appendLine("|---|---:|---:|---:|---:|")
    modules.forEach { (path, fields) ->
        val composables = fields["totalComposables"]
        val classes = fields["totalClasses"]
        if (composables == null || classes == null) {
            appendLine("| [`$path`](${stabilityReportName(path)}) | — | — | — | — |")
            return@forEach
        }
        appendLine(
            "| [`$path`](${stabilityReportName(path)}) | $composables | ${percent(fields["skippableComposables"] ?: 0, composables)} " +
                "| $classes | ${percent(fields["effectivelyStableClasses"] ?: 0, classes)} |",
        )
    }
}

private const val INDEX_LINK = "README.md"
