package io.thernal.buildkit.buildlogic.modules.graph

import java.util.Locale

/** A report page: title, links back to [INDEX_PAGE], and [body] between them. */
internal fun reportPage(
    title: String,
    task: String,
    body: StringBuilder.() -> Unit,
): String = buildString {
    appendLine("# $title")
    appendLine()
    appendLine("[← Module report]($INDEX_PAGE) · generated by `./gradlew $task`")
    appendLine()
    body()
    appendLine()
    appendLine("[← Module report]($INDEX_PAGE)")
}

internal fun indexPage(
    modules: List<ModuleNode>,
    conditions: Map<String, Condition>,
    waves: List<List<String>>,
    task: String,
): String = buildString {
    appendLine("# Module Report")
    appendLine()
    appendLine("Generated by `./gradlew $task`. Do not edit by hand.")
    appendLine()
    appendLine(severitySummary(conditions.values.toList()))
    appendLine()
    appendLine("| Page | What it answers |")
    appendLine("|---|---|")
    appendLine("| [Health](health.md) | Which modules need attention, and what to do about each |")
    appendLine("| [Build waves](build-waves.md) | What compiles in parallel, and in what order to read the code |")
    GRAPH_VIEWS.forEach { view ->
        appendLine("| [${view.title}](${view.file}) | ${modules.count(view.include)} modules |")
    }
    appendLine("| [Coupling metrics](metrics.md) | The raw afferent, efferent, instability and abstractness figures |")
    appendLine()
    appendLine("## At a glance")
    appendLine()
    appendLine("| | |")
    appendLine("|---|---|")
    appendLine("| Modules | ${modules.size} |")
    appendLine("| Build depth | ${waves.size} waves |")
    appendLine("| Widest wave | ${waves.maxOfOrNull(List<String>::size) ?: 0} modules in parallel |")
    appendNeedsALook(conditions)
}

private fun StringBuilder.appendNeedsALook(conditions: Map<String, Condition>) {
    val flagged = conditions.entries
        .filter { entry -> entry.value.severity != Severity.HEALTHY }
        .sortedWith(compareBy({ it.value.severity.ordinal }, { it.value.ordinal }, { it.key }))
    if (flagged.isEmpty()) return
    appendLine()
    appendLine("## Needs a look")
    appendLine()
    flagged.forEach { (path, condition) ->
        appendLine("- ${condition.severity.marker} `$path` — **${condition.title}**. ${condition.action}")
    }
    appendLine()
    appendLine("[Full health table](health.md)")
}

private fun severitySummary(conditions: List<Condition>): String {
    val counts = Severity.entries.associateWith { severity ->
        conditions.count { condition -> condition.severity == severity }
    }
    return Severity.entries.joinToString(separator = " · ") { severity ->
        "${severity.marker} ${counts.getValue(severity)} ${severity.label.lowercase(Locale.ROOT)}"
    }
}

internal fun healthBody(
    modules: List<ModuleNode>,
    metrics: Map<String, ModuleMetrics>,
    conditions: Map<String, Condition>,
): String = buildString {
    appendLine("Each module gets the first condition that applies to it, so the verdict is one thing to act on")
    appendLine("rather than a row of numbers. **Used by** counts the modules that depend on it, **depends on**")
    appendLine("the modules it needs.")
    appendLine()
    Condition.entries.forEach { condition ->
        appendLine("- ${condition.severity.marker} **${condition.title}** — ${condition.meaning} ${condition.action}")
    }
    appendLine()
    appendLine("| | Module | Condition | Used by | Depends on |")
    appendLine("|---|---|---|---:|---:|")
    modules
        .sortedWith(
            compareBy<ModuleNode> { conditions.getValue(it.path).severity.ordinal }
                .thenBy { conditions.getValue(it.path).ordinal }
                .thenBy(ModuleNode::path),
        )
        .forEach { module ->
            val condition = conditions.getValue(module.path)
            val entry = metrics.getValue(module.path)
            appendLine(
                "| ${condition.severity.marker} | `${module.path}` | ${condition.title} " +
                    "| ${entry.afferent} | ${entry.efferent} |",
            )
        }
}

internal fun buildWavesBody(waves: List<List<String>>): String = buildString {
    appendLine("A wave is everything that can compile at once: wave 0 depends on no other module, and each")
    appendLine("later wave waits only for the ones before it. The build is at least this many steps deep no")
    appendLine("matter how many cores are available, so a deep graph is a slow graph.")
    appendLine()
    appendLine("Read the code in the same order. Wave 0 stands on its own; by the time you reach a later")
    appendLine("wave you have already seen everything it builds on.")
    appendLine()
    appendLine("| Wave | Parallel |")
    appendLine("|---:|---:|")
    waves.forEachIndexed { index, wave -> appendLine("| $index | ${wave.size} |") }
    appendLine()
    waves.forEachIndexed { index, wave ->
        appendLine("## Wave $index")
        appendLine()
        appendLine("${wave.size} modules, all buildable at the same time.")
        appendLine()
        append(waveRow(wave))
        appendLine()
    }
}

internal fun arrowLegend(): String = buildString {
    appendLine("An arrow points from a module to one it depends on. Node fill marks the role, and a 🔴 or 🟡")
    appendLine("repeats the verdict from [Health](health.md).")
}

internal fun metricsBody(metrics: List<ModuleMetrics>): String = buildString {
    appendLine("`Ca` counts the modules that depend on this one, `Ce` the modules it depends on.")
    appendLine("`I` is instability, `Ce / (Ca + Ce)`. `A` is abstractness, the share of declarations that are")
    appendLine("interfaces or abstract classes. `D` is `|A + I - 1|`, the distance from the main sequence.")
    appendLine()
    appendLine("A `wiring` module reads as fully abstract because a binding container is an interface, so its")
    appendLine("`D` is noise rather than a finding.")
    appendLine()
    appendLine("| Module | Ca | Ce | I | A | D | Declarations |")
    appendLine("|---|---:|---:|---:|---:|---:|---:|")
    metrics.sortedBy(ModuleMetrics::path).forEach { entry ->
        appendLine(
            "| `${entry.path}` | ${entry.afferent} | ${entry.efferent} | ${format(entry.instability)} " +
                "| ${format(entry.abstractness)} | ${format(entry.distance)} | ${entry.declarations} |",
        )
    }
}

private fun format(value: Double): String = String.format(Locale.ROOT, "%.2f", value)
